In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
data=pd.read_csv('googleplaystore.csv')
data.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [4]:
data.shape

(10841, 13)

In [5]:
data.dropna(inplace=True)
data

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
5                             Paper flowers instructions       ART_AND_DESIGN   
6                Smoke Effect Photo Maker - Smoke Editor       ART_AND_DESIGN   
7                                       Infinite Painter       ART_AND_DESIGN   
8                                   Garden Coloring Book       ART_AND_DESIGN   
9                          Kids Paint Free - Drawing Fun       ART_AND_DESIGN   
10                               Text on Photo - Fonteee       ART_AND_DESIGN   
11               Name Art Photo Editor - Focus n Filters       ART_AND_DESIGN   
12                        Tattoo Name On My Photo Editor       ART_AND_DESIGN   
13                                 Mandala Coloring Book       ART_AND_DESIGN   
14       3D Color Pixel by Number - Sandbox Art Coloring       ART_AND_DESIGN   
16          Photo Designer - Write your name with shapes       ART_AND_DESIGN   
17                              350 Diy Room Decor Ideas       ART_AND_DESIGN   
18                         FlipaClip - Cartoon animation       ART_AND_DESIGN   
19                                          ibis Paint X       ART_AND_DESIGN   
20                           Logo Maker - Small Business       ART_AND_DESIGN   
21             Boys Photo Editor - Six Pack & Men's Suit       ART_AND_DESIGN   
22               Superheroes Wallpapers | 4K Backgrounds       ART_AND_DESIGN   
24                           HD Mickey Minnie Wallpapers       ART_AND_DESIGN   
25                            Harley Quinn wallpapers HD       ART_AND_DESIGN   
26                         Colorfit - Drawing & Coloring       ART_AND_DESIGN   
27                                 Animated Photo Editor       ART_AND_DESIGN   
28                                 Pencil Sketch Drawing       ART_AND_DESIGN   
29                       Easy Realistic Drawing Tutorial       ART_AND_DESIGN   
30                        Pink Silver Bow Keyboard Theme       ART_AND_DESIGN   
31                                     Art Drawing Ideas       ART_AND_DESIGN   
...                                                  ...                  ...   
10795                           Reindeer VPN - Proxy VPN                TOOLS   
10796   Inf VPN - Global Proxy & Unlimited Free WIFI VPN                TOOLS   
10797                              Fuel Rewards® program            LIFESTYLE   
10799                                     Fr Daoud Lamei               SOCIAL   
10800                                          FR Roster                TOOLS   
10801                                Fr Ignacio Outreach               FAMILY   
10802                                FR: My Famous Lover               FAMILY   
10803                       Fatal Raid - No.1 Mobile FPS                 GAME   
10804                                       Poker Pro.Fr                 GAME   
10805                                      Scoreboard FR            LIFESTYLE   
10809              Castle Clash: RPG War and Strategy FR               FAMILY   
10810                                  Fr Lupupa Sermons             BUSINESS   
10812                                      Fr Agnel Pune               FAMILY   
10814                               FR: My Secret Pets!                FAMILY   
10815                          Golden Dictionary (FR-AR)  BOOKS_AND_REFERENCE   
10817                               HTC Sense Input - FR                TOOLS   
10819                                          Fanfic-FR  BOOKS_AND_REFERENCE   
10820                                    Fr. Daoud Lamei               FAMILY   
108

In [6]:
data.shape

(9360, 13)

In [7]:
user_review=pd.read_csv('googleplaystore_user_reviews.csv')
user_review.head()

App                                  Translated_Review  \
0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...   
1  10 Best Foods for You    This help eating healthy exercise regular basis   
2  10 Best Foods for You                                                NaN   
3  10 Best Foods for You         Works great especially going grocery store   
4  10 Best Foods for You                                       Best idea us   

  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  
0  Positive                1.00                0.533333  
1  Positive                0.25                0.288462  
2       NaN                 NaN                     NaN  
3  Positive                0.40                0.875000  
4  Positive                1.00                0.300000

In [8]:
user_review.shape

(64295, 5)

In [9]:
data['Size'].head()

0     19M
1     14M
2    8.7M
3     25M
4    2.8M
Name: Size, dtype: object

In [10]:
data['Size'].nunique()

413

In [11]:
data['Installs'].head()

0        10,000+
1       500,000+
2     5,000,000+
3    50,000,000+
4       100,000+
Name: Installs, dtype: object

In [12]:
data['Installs'].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '100+', '500+', '10+',
       '5+', '50+', '1+'], dtype=object)

In [13]:
data.Installs = data.Installs.apply(lambda x: x.replace(',',''))
data.Installs = data.Installs.apply(lambda x: x.replace('+',''))
data.Installs = data.Installs.apply(lambda x: int(x))

In [14]:
data['Installs'].nunique()

19

In [15]:
data['Installs'].head()

0       10000
1      500000
2     5000000
3    50000000
4      100000
Name: Installs, dtype: int64

In [16]:
data.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size  Installs  Type Price Content Rating  \
0     159   19M     10000  Free     0       Everyone   
1     967   14M    500000  Free     0       Everyone   
2   87510  8.7M   5000000  Free     0       Everyone   
3  215644   25M  50000000  Free     0           Teen   
4     967  2.8M    100000  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [17]:
data['Reviews'] = data['Reviews'].apply(lambda x: int(x))                        #converting object to int

In [18]:
final_review=data[data.Reviews > 5000000]
final_review

App             Category  \
335             Messenger – Text and Video Chat for Free        COMMUNICATION   
336                                   WhatsApp Messenger        COMMUNICATION   
338                         Google Chrome: Fast & Secure        COMMUNICATION   
342                                      Viber Messenger        COMMUNICATION   
351                        Opera Mini - fast web browser        COMMUNICATION   
365                                               WeChat        COMMUNICATION   
378          UC Browser - Fast Download Private & Secure        COMMUNICATION   
381                                   WhatsApp Messenger        COMMUNICATION   
382             Messenger – Text and Video Chat for Free        COMMUNICATION   
385                                      Viber Messenger        COMMUNICATION   
390                                               WeChat        COMMUNICATION   
391                        Skype - free IM & video calls        COMMUNICATION   
403                          LINE: Free Calls & Messages        COMMUNICATION   
406                          BBM - Free Calls & Messages        COMMUNICATION   
411                         Google Chrome: Fast & Secure        COMMUNICATION   
417                        Opera Mini - fast web browser        COMMUNICATION   
420          UC Browser - Fast Download Private & Secure        COMMUNICATION   
431                                      Viber Messenger        COMMUNICATION   
449    Truecaller: Caller ID, SMS spam blocking & Dialer        COMMUNICATION   
467                                      Viber Messenger        COMMUNICATION   
468                        Skype - free IM & video calls        COMMUNICATION   
469                                               WeChat        COMMUNICATION   
474                          LINE: Free Calls & Messages        COMMUNICATION   
699                       Duolingo: Learn Languages Free            EDUCATION   
784                       Duolingo: Learn Languages Free            EDUCATION   
799                       Duolingo: Learn Languages Free            EDUCATION   
826                       Duolingo: Learn Languages Free            EDUCATION   
855                                              Netflix        ENTERTAINMENT   
865                                    Google Play Games        ENTERTAINMENT   
904                                              Netflix        ENTERTAINMENT   
...                                                  ...                  ...   
4227                                          slither.io                 GAME   
4234                       Skype - free IM & video calls        COMMUNICATION   
4365                                           MX Player        VIDEO_PLAYERS   
4421                       Opera Mini - fast web browser        COMMUNICATION   
4448    PicsArt Photo Studio: Collage Maker & Pic Editor          PHOTOGRAPHY   
4566                          SHAREit - Transfer & Share                TOOLS   
4568     360 Security - Free Antivirus, Booster, Cleaner                TOOLS   
4602   Truecaller: Caller ID, SMS spam blocking & Dialer        COMMUNICATION   
4676                                     Viber Messenger        COMMUNICATION   
4688              VivaVideo - Video Editor & Photo Movie        VIDEO_PLAYERS   
4712                                              WeChat        COMMUNICATION   
4717   Waze - GPS, Maps, Traffic Alerts & Live Naviga...  MAPS_AND_NAVIGATION   
4808   Avast Mobile Security 2018 - Antivirus & App Lock                TOOLS   
4812    GO Launcher - 3D parallax Themes & HD Wallpapers      PERSONALIZATION   
5395                                       Google Photos          PHOTOGRAPHY   
5417                           Mobile Legends: Bang Bang                 GAME   
5695             AVG AntiVirus 2018 for Android Security                TOOLS   
5856                                   Google Play Games               FAMILY   
637

In [19]:
data1=final_review.drop(columns=['Category','Size','Type','Price','Content Rating','Current Ver','Genres','Last Updated','Android Ver'])
data1.head()

App  Rating   Reviews    Installs
335  Messenger – Text and Video Chat for Free     4.0  56642847  1000000000
336                        WhatsApp Messenger     4.4  69119316  1000000000
338              Google Chrome: Fast & Secure     4.3   9642995  1000000000
342                           Viber Messenger     4.3  11334799   500000000
351             Opera Mini - fast web browser     4.5   5149854   100000000

In [20]:
user_review['Sentiment'].replace('Positive',1,inplace=True)
user_review['Sentiment'].replace('Neutral',0,inplace=True)
user_review['Sentiment'].replace('Negative',-1,inplace=True)

In [21]:
user_review.drop(columns=['Translated_Review','Sentiment_Polarity','Sentiment_Subjectivity'],inplace=True)

In [22]:
user_review.head()

App  Sentiment
0  10 Best Foods for You        1.0
1  10 Best Foods for You        1.0
2  10 Best Foods for You        NaN
3  10 Best Foods for You        1.0
4  10 Best Foods for You        1.0

In [23]:
mask1=user_review[user_review['Sentiment']==1.0]
mask1=mask1['App'].value_counts().reset_index()
mask1=mask1.rename(columns={'index':'App','App':'Sentiment(1)'})

In [24]:
mask2=user_review[user_review['Sentiment']==0.0]
mask2=mask2['App'].value_counts().reset_index()
mask2=mask2.rename(columns={'index':'App','App':'Sentiment(0)'})

In [25]:
mask3=user_review[user_review['Sentiment']==-1.0]
mask3=mask3['App'].value_counts().reset_index()
mask3=mask3.rename(columns={'index':'App','App':'Sentiment(-1)'})

In [26]:
mask=mask2.merge(mask1,left_on='App',right_on='App')
mask=mask3.merge(mask,left_on='App',right_on='App')
mask.head()

App  Sentiment(-1)  Sentiment(0)  Sentiment(1)
0    Angry Birds Classic            147             2           124
1       Candy Crush Saga            126            12           102
2             Bowmasters            119            24           169
3            8 Ball Pool            106             9           104
4  Candy Crush Soda Saga             96             8            62

In [27]:
data2=data1.merge(mask,left_on='App',right_on='App')
data2.head()

App  Rating   Reviews   Installs  Sentiment(-1)  \
0     BBM - Free Calls & Messages     4.3  12842860  100000000              8   
1     BBM - Free Calls & Messages     4.3  12843436  100000000              8   
2  Duolingo: Learn Languages Free     4.7   6289924  100000000             34   
3  Duolingo: Learn Languages Free     4.7   6290507  100000000             34   
4  Duolingo: Learn Languages Free     4.7   6290507  100000000             34   

   Sentiment(0)  Sentiment(1)  
0             9            18  
1             9            18  
2             6           200  
3             6           200  
4             6           200

In [28]:
X=data2.iloc[:,2:7].values
X

array([[  12842860,  100000000,          8,          9,         18],
       [  12843436,  100000000,          8,          9,         18],
       [   6289924,  100000000,         34,          6,        200],
       [   6290507,  100000000,         34,          6,        200],
       [   6290507,  100000000,         34,          6,        200],
       [   6290507,  100000000,         34,          6,        200],
       [   6294400,  100000000,         34,          6,        200],
       [   6294397,  100000000,         34,          6,        200],
       [   6297590,  100000000,         34,          6,        200],
       [  22426677,  500000000,        126,         12,        102],
       [  22428456,  500000000,        126,         12,        102],
       [  22428456,  500000000,        126,         12,        102],
       [  22429716,  500000000,        126,         12,        102],
       [  22430188,  500000000,        126,         12,        102],
       [  22430188,  500000000,   

In [29]:
y=data2.iloc[:,1:2].values
y

array([[4.3],
       [4.3],
       [4.7],
       [4.7],
       [4.7],
       [4.7],
       [4.7],
       [4.7],
       [4.7],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.5],
       [4.5],
       [4.5],
       [4.5],
       [4.5],
       [4.5],
       [4.5],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.5],
       [4.5],
       [4.5],
       [4.5],
       [4.1],
       [4.1],
       [4.3],
       [4.3],
       [4.4],
       [4.4],
       [4.5],
       [4.5],
       [4.5],
       [4.5],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.5],
       [4.5],
       [4.6],
       [4.6],
       [4.5],
       [4.5],
       [4.5],
       [4.3]])

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=9)
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [31]:
y_pred=regressor.predict(X_test)


In [32]:
from sklearn.metrics import r2_score


In [33]:
X_test

array([[   7614407,  100000000,         43,         21,         46],
       [  22430188,  500000000,        126,         12,        102],
       [   6294400,  100000000,         34,          6,        200],
       [   6294397,  100000000,         34,          6,        200],
       [   5465624,  100000000,         81,          5,        136],
       [   6289924,  100000000,         34,          6,        200],
       [   8595964,  500000000,         14,          3,         12],
       [   5476569,  100000000,         81,          5,        136],
       [  14201891,  100000000,        106,          9,        104],
       [  10859051, 1000000000,         47,          1,        143],
       [   7614130,  100000000,         43,         21,         46],
       [  14198602,  100000000,        106,          9,        104],
       [   6003590,  100000000,          4,          5,         19]],
      dtype=int64)

In [34]:
y_test

array([[4.4],
       [4.4],
       [4.7],
       [4.7],
       [4.5],
       [4.7],
       [4.3],
       [4.5],
       [4.5],
       [4.5],
       [4.4],
       [4.5],
       [4.4]])

In [35]:
X_train

array([[   6198880,  100000000,         96,          8,         62],
       [   6290507,  100000000,         34,          6,        200],
       [  22419455,  500000000,        126,         12,        102],
       [  14200344,  100000000,        106,          9,        104],
       [   5282578,  100000000,          5,          2,          9],
       [   6012719,  100000000,          4,          5,         19],
       [  10858538, 1000000000,         47,          1,        143],
       [   6290507,  100000000,         34,          6,        200],
       [   6290507,  100000000,         34,          6,        200],
       [   6297590,  100000000,         34,          6,        200],
       [   8389714,  100000000,         31,          3,         39],
       [  14184910,  100000000,        106,          9,        104],
       [   5534114,  100000000,         81,          5,        136],
       [   5565856,  100000000,        147,          2,        124],
       [  78128208, 1000000000,   

In [36]:
y_train

array([[4.4],
       [4.7],
       [4.4],
       [4.5],
       [4.4],
       [4.4],
       [4.5],
       [4.7],
       [4.7],
       [4.7],
       [4.5],
       [4.5],
       [4.5],
       [4.4],
       [4.1],
       [4.4],
       [4.5],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.4],
       [4.5],
       [4.4],
       [4.4],
       [4.6],
       [4.5],
       [4.4],
       [4.4],
       [4.3],
       [4.5],
       [4.4],
       [4.5],
       [4.5],
       [4.3],
       [4.5],
       [4.4],
       [4.4],
       [4.4],
       [4.5],
       [4.1],
       [4.4],
       [4.6],
       [4.3],
       [4.5],
       [4.5],
       [4.4],
       [4.4],
       [4.4],
       [4.3]])

In [37]:
r2_score(y_test,y_pred)

0.8732171184455416